name: DITA-OT-OCRD-FAQ_V4
on:
  push:
    tags:
      - 'v5[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:

      
      - name: Git checkout
        uses: actions/checkout@v3
      
      - name: pwd
        run: |
            pwd
            ls

      
